<?php

use Illuminate\Database\Seeder;

class LanguageSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('languages')->truncate();
        
        \DB::table('languages')->insert(array (
            0 => 
            array (
                'id' => 1,
                'code' => 'ab',
                'name' => 'аҧсуа бызшәа, аҧсшәа',
                'english_name' => 'Abkhazian',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'code' => 'aa',
                'name' => 'Afaraf',
                'english_name' => 'Afar',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'code' => 'af',
                'name' => 'Afrikaans',
                'english_name' => 'Afrikaans',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'code' => 'ak',
                'name' => 'Akan',
                'english_name' => 'Akan',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'code' => 'sq',
                'name' => 'Shqip',
                'english_name' => 'Albanian',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'code' => 'am',
                'name' => 'አማርኛ',
                'english_name' => 'Amharic',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'code' => 'ar',
                'name' => 'العربية',
                'english_name' => 'Arabic',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'code' => 'an',
                'name' => 'aragonés',
                'english_name' => 'Aragonese',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'code' => 'hy',
                'name' => 'Հայերեն',
                'english_name' => 'Armenian',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'code' => 'as',
                'name' => 'অসমীয়া',
                'english_name' => 'Assamese',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'code' => 'av',
                'name' => 'авар мацӀ, магӀарул мацӀ',
                'english_name' => 'Avaric',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'code' => 'ae',
                'name' => 'avesta',
                'english_name' => 'Avestan',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'code' => 'ay',
                'name' => 'aymar aru',
                'english_name' => 'Aymara',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'code' => 'az',
                'name' => 'azərbaycan dili',
                'english_name' => 'Azerbaijani',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'code' => 'bm',
                'name' => 'bamanankan',
                'english_name' => 'Bambara',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'code' => 'ba',
                'name' => 'башҡорт теле',
                'english_name' => 'Bashkir',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'code' => 'eu',
                'name' => 'euskara, euskera',
                'english_name' => 'Basque',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'code' => 'be',
                'name' => 'беларуская мова',
                'english_name' => 'Belarusian',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'code' => 'bn',
                'name' => 'বাংলা',
                'english_name' => 'Bengali',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'code' => 'bh',
                'name' => 'भोजपुरी',
                'english_name' => 'Bihari languages',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'code' => 'bi',
                'name' => 'Bislama',
                'english_name' => 'Bislama',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'code' => 'bs',
                'name' => 'bosanski jezik',
                'english_name' => 'Bosnian',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'code' => 'br',
                'name' => 'brezhoneg',
                'english_name' => 'Breton',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'code' => 'bg',
                'name' => 'български език',
                'english_name' => 'Bulgarian',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'code' => 'my',
                'name' => 'ဗမာစာ',
                'english_name' => 'Burmese',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'code' => 'ca',
                'name' => 'català, valencià',
                'english_name' => 'Catalan, Valencian',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'code' => 'ch',
                'name' => 'Chamoru',
                'english_name' => 'Chamorro',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'code' => 'ce',
                'name' => 'нохчийн мотт',
                'english_name' => 'Chechen',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'code' => 'ny',
                'name' => 'chiCheŵa, chinyanja',
                'english_name' => 'Chichewa, Chewa, Nyanja',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'code' => 'zh',
            'name' => '中文 (Zhōngwén), 汉语, 漢語',
                'english_name' => 'Chinese',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'code' => 'cv',
                'name' => 'чӑваш чӗлхи',
                'english_name' => 'Chuvash',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'code' => 'kw',
                'name' => 'Kernewek',
                'english_name' => 'Cornish',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'code' => 'co',
                'name' => 'corsu, lingua corsa',
                'english_name' => 'Corsican',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'code' => 'cr',
                'name' => 'ᓀᐦᐃᔭᐍᐏᐣ',
                'english_name' => 'Cree',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'code' => 'hr',
                'name' => 'hrvatski jezik',
                'english_name' => 'Croatian',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'code' => 'cs',
                'name' => 'čeština, český jazyk',
                'english_name' => 'Czech',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'code' => 'da',
                'name' => 'dansk',
                'english_name' => 'Danish',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'code' => 'dv',
                'name' => 'ދިވެހި',
                'english_name' => 'Divehi, Dhivehi, Maldivian',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'code' => 'nl',
                'name' => 'Nederlands, Vlaams',
                'english_name' => '	Dutch, Flemish',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'code' => 'dz',
                'name' => 'རྫོང་ཁ',
                'english_name' => 'Dzongkha',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'code' => 'en',
                'name' => 'English',
                'english_name' => 'English',
                'status_public' => 'enabled',
                'status_staff' => 'enabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'code' => 'eo',
                'name' => 'Esperanto',
                'english_name' => 'Esperanto',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'code' => 'et',
                'name' => 'eesti, eesti keel',
                'english_name' => 'Estonian',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'code' => 'ee',
                'name' => 'Eʋegbe',
                'english_name' => 'Ewe',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'code' => 'fo',
                'name' => 'føroyskt',
                'english_name' => 'Faroese',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'code' => 'fj',
                'name' => 'vosa Vakaviti',
                'english_name' => 'Fijian',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'code' => 'fi',
                'name' => 'suomi, suomen kieli',
                'english_name' => 'Finnish',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'code' => 'fr',
                'name' => 'français, langue française',
                'english_name' => 'French',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'code' => 'ff',
                'name' => 'Fulfulde, Pulaar, Pular',
                'english_name' => 'Fulah',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'code' => 'gl',
                'name' => 'Galego',
                'english_name' => 'Galician',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'code' => 'ka',
                'name' => 'ქართული',
                'english_name' => 'Georgian',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'code' => 'de',
                'name' => 'Deutsch',
                'english_name' => 'German',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'code' => 'el',
                'name' => 'ελληνικά',
            'english_name' => 'Greek, Modern (1453-)',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'code' => 'gn',
                'name' => 'Avañe\'ẽ',
                'english_name' => 'Guarani',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'code' => 'gu',
                'name' => 'ગુજરાતી',
                'english_name' => 'Gujarati',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'code' => 'ht',
                'name' => 'Kreyòl ayisyen',
                'english_name' => 'Haitian, Haitian Creole',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'code' => 'ha',
            'name' => 'هَوُسَ (Hausa)',
                'english_name' => 'Hausa',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'code' => 'he',
                'name' => 'עברית',
                'english_name' => 'Hebrew',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'code' => 'hz',
                'name' => 'Otjiherero',
                'english_name' => 'Herero',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'code' => 'hi',
                'name' => 'हिन्दी, हिंदी',
                'english_name' => 'Hindi',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'code' => 'ho',
                'name' => 'Hiri Motu',
                'english_name' => 'Hiri Motu',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'code' => 'hu',
                'name' => 'magyar',
                'english_name' => 'Hungarian',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'code' => 'ia',
                'name' => 'Interlingua',
            'english_name' => 'Interlingua (International Auxiliary Language Association)',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'code' => 'id',
                'name' => 'Bahasa Indonesia',
                'english_name' => 'Indonesian',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'code' => 'ie',
            'name' => '(originally:) Occidental, (after WWII:) Interlingue',
                'english_name' => 'Interlingue, Occidental',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'code' => 'ga',
                'name' => 'Gaeilge',
                'english_name' => 'Irish',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'code' => 'ig',
                'name' => 'Asụsụ Igbo',
                'english_name' => 'Igbo',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'code' => 'ik',
                'name' => 'Iñupiaq, Iñupiatun',
                'english_name' => 'Inupiaq',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'code' => 'io',
                'name' => 'Ido',
                'english_name' => 'Ido',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'code' => 'is',
                'name' => 'Íslenska',
                'english_name' => 'Icelandic',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'code' => 'it',
                'name' => 'Italiano',
                'english_name' => 'Italian',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'code' => 'iu',
                'name' => 'ᐃᓄᒃᑎᑐᑦ',
                'english_name' => 'Inuktitut',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'code' => 'ja',
            'name' => '日本語 (にほんご)',
                'english_name' => 'Japanese',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'code' => 'jv',
                'name' => 'ꦧꦱꦗꦮ, Basa Jawa',
                'english_name' => 'Javanese',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'code' => 'kl',
                'name' => 'kalaallisut, kalaallit oqaasii',
                'english_name' => 'Kalaallisut, Greenlandic',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'code' => 'kn',
                'name' => 'ಕನ್ನಡ',
                'english_name' => 'Kannada',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'code' => 'kr',
                'name' => 'Kanuri',
                'english_name' => 'Kanuri',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'code' => 'ks',
                'name' => 'कश्मीरी, كشميري',
                'english_name' => 'Kashmiri',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'code' => 'kk',
                'name' => 'қазақ тілі',
                'english_name' => 'Kazakh',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'code' => 'km',
                'name' => 'ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ',
                'english_name' => 'Central Khmer',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'code' => 'ki',
                'name' => 'Gĩkũyũ',
                'english_name' => 'Kikuyu, Gikuyu',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'code' => 'rw',
                'name' => 'Ikinyarwanda',
                'english_name' => 'Kinyarwanda',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'code' => 'ky',
                'name' => 'Кыргызча, Кыргыз тили',
                'english_name' => 'Kirghiz, Kyrgyz',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'code' => 'kv',
                'name' => 'коми кыв',
                'english_name' => 'Komi',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'code' => 'kg',
                'name' => 'Kikongo',
                'english_name' => 'Kongo',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'code' => 'ko',
                'name' => '한국어',
                'english_name' => '	Korean',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'code' => 'ku',
                'name' => 'Kurdî, کوردی',
                'english_name' => 'Kurdish',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'code' => 'kj',
                'name' => 'Kuanyama',
                'english_name' => 'Kuanyama, Kwanyama',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'code' => 'la',
                'name' => 'latine, lingua latina',
                'english_name' => 'Latin',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'code' => 'lb',
                'name' => 'Lëtzebuergesch',
                'english_name' => 'Luxembourgish, Letzeburgesch',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'code' => 'lg',
                'name' => 'Luganda',
                'english_name' => 'Ganda',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'code' => 'li',
                'name' => 'Limburgs',
                'english_name' => 'Limburgan, Limburger, Limburgish',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'code' => 'ln',
                'name' => 'Lingála',
                'english_name' => 'Lingala',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'code' => 'lo',
                'name' => 'ພາສາລາວ',
                'english_name' => 'Lao',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'code' => 'lt',
                'name' => 'lietuvių kalba',
                'english_name' => 'Lithuanian',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'code' => 'lu',
                'name' => 'Kiluba',
                'english_name' => 'Luba-Katanga',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'code' => 'lv',
                'name' => 'latviešu valoda',
                'english_name' => 'Latvian',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'code' => 'gv',
                'name' => 'Gaelg, Gailck',
                'english_name' => 'Manx',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'code' => 'mk',
                'name' => 'македонски јазик',
                'english_name' => 'Macedonian',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'code' => 'mg',
                'name' => 'fiteny malagasy',
                'english_name' => 'Malagasy',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            100 => 
            array (
                'id' => 101,
                'code' => 'ms',
                'name' => 'Bahasa Melayu, بهاس ملايو',
                'english_name' => 'Malay',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            101 => 
            array (
                'id' => 102,
                'code' => 'ml',
                'name' => 'മലയാളം',
                'english_name' => 'Malayalam',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            102 => 
            array (
                'id' => 103,
                'code' => 'mt',
                'name' => 'Malti',
                'english_name' => 'Maltese',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            103 => 
            array (
                'id' => 104,
                'code' => 'mi',
                'name' => 'te reo Māori',
                'english_name' => 'Maori',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            104 => 
            array (
                'id' => 105,
                'code' => 'mr',
                'name' => 'मराठी',
                'english_name' => 'Marathi',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            105 => 
            array (
                'id' => 106,
                'code' => 'mh',
                'name' => 'Kajin M̧ajeļ',
                'english_name' => 'Marshallese',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            106 => 
            array (
                'id' => 107,
                'code' => 'mn',
                'name' => 'Монгол хэл',
                'english_name' => 'Mongolian',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            107 => 
            array (
                'id' => 108,
                'code' => 'na',
                'name' => 'Dorerin Naoero',
                'english_name' => 'Nauru',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            108 => 
            array (
                'id' => 109,
                'code' => 'nv',
                'name' => 'Diné bizaad',
                'english_name' => 'Navajo, Navaho',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            109 => 
            array (
                'id' => 110,
                'code' => 'nd',
                'name' => 'isiNdebele',
                'english_name' => 'North Ndebele',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            110 => 
            array (
                'id' => 111,
                'code' => 'ne',
                'name' => 'नेपाली',
                'english_name' => 'Nepali',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            111 => 
            array (
                'id' => 112,
                'code' => 'ng',
                'name' => 'Owambo',
                'english_name' => 'Ndonga',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            112 => 
            array (
                'id' => 113,
                'code' => 'nb',
                'name' => 'Norsk Bokmål',
                'english_name' => 'Norwegian Bokmål',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            113 => 
            array (
                'id' => 114,
                'code' => 'nn',
                'name' => 'Norsk Nynorsk',
                'english_name' => 'Norwegian Nynorsk',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            114 => 
            array (
                'id' => 115,
                'code' => 'no',
                'name' => 'Norsk',
                'english_name' => 'Norwegian',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            115 => 
            array (
                'id' => 116,
                'code' => 'ii',
                'name' => 'ꆈꌠ꒿ Nuosuhxop',
                'english_name' => 'Sichuan Yi, Nuosu',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            116 => 
            array (
                'id' => 117,
                'code' => 'nr',
                'name' => 'isiNdebele',
                'english_name' => 'South Ndebele',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            117 => 
            array (
                'id' => 118,
                'code' => 'oc',
                'name' => 'occitan, lenga d\'òc',
                'english_name' => 'Occitan',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            118 => 
            array (
                'id' => 119,
                'code' => 'oj',
                'name' => 'ᐊᓂᔑᓈᐯᒧᐎᓐ',
                'english_name' => 'Ojibwa',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            119 => 
            array (
                'id' => 120,
                'code' => 'cu',
                'name' => 'ѩзыкъ словѣньскъ',
                'english_name' => 'Church Slavic, Old Slavonic, Church Slavonic, Old Bulgarian, Old Church Slavonic',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            120 => 
            array (
                'id' => 121,
                'code' => 'om',
                'name' => 'Afaan Oromoo',
                'english_name' => 'Oromo',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            121 => 
            array (
                'id' => 122,
                'code' => 'or',
                'name' => 'ଓଡ଼ିଆ',
                'english_name' => 'Oriya',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            122 => 
            array (
                'id' => 123,
                'code' => 'os',
                'name' => 'ирон æвзаг',
                'english_name' => 'Ossetian, Ossetic',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            123 => 
            array (
                'id' => 124,
                'code' => 'pa',
                'name' => 'ਪੰਜਾਬੀ, پنجابی',
                'english_name' => 'Punjabi, Panjabi',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            124 => 
            array (
                'id' => 125,
                'code' => 'pi',
                'name' => 'पालि, पाळि',
                'english_name' => 'Pali',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            125 => 
            array (
                'id' => 126,
                'code' => 'fa',
                'name' => 'فارسی',
                'english_name' => 'Persian',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            126 => 
            array (
                'id' => 127,
                'code' => 'pl',
                'name' => 'język polski, polszczyzna',
                'english_name' => 'Polish',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            127 => 
            array (
                'id' => 128,
                'code' => 'ps',
                'name' => 'پښتو',
                'english_name' => 'Pashto, Pushto',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            128 => 
            array (
                'id' => 129,
                'code' => 'pt',
                'name' => 'Português',
                'english_name' => 'Portuguese',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            129 => 
            array (
                'id' => 130,
                'code' => 'qu',
                'name' => 'Runa Simi, Kichwa',
                'english_name' => 'Quechua',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            130 => 
            array (
                'id' => 131,
                'code' => 'rm',
                'name' => 'Rumantsch Grischun',
                'english_name' => 'Romansh',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            131 => 
            array (
                'id' => 132,
                'code' => 'rn',
                'name' => 'Ikirundi',
                'english_name' => 'Rundi',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            132 => 
            array (
                'id' => 133,
                'code' => 'ro',
                'name' => 'Română',
                'english_name' => 'Romanian, Moldavian, Moldovan',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            133 => 
            array (
                'id' => 134,
                'code' => 'ru',
                'name' => 'русский',
                'english_name' => 'Russian',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            134 => 
            array (
                'id' => 135,
                'code' => 'sa',
                'name' => 'संस्कृतम्',
                'english_name' => 'Sanskrit',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            135 => 
            array (
                'id' => 136,
                'code' => 'sc',
                'name' => 'sardu',
                'english_name' => 'Sardinian',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            136 => 
            array (
                'id' => 137,
                'code' => 'sd',
                'name' => 'सिन्धी, سنڌي، سندھی',
                'english_name' => 'Sindhi',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            137 => 
            array (
                'id' => 138,
                'code' => 'se',
                'name' => 'Davvisámegiella',
                'english_name' => 'Northern Sami',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            138 => 
            array (
                'id' => 139,
                'code' => 'sm',
                'name' => 'gagana fa\'a Samoa',
                'english_name' => 'Samoan',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            139 => 
            array (
                'id' => 140,
                'code' => 'sg',
                'name' => 'yângâ tî sängö',
                'english_name' => 'Sango',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            140 => 
            array (
                'id' => 141,
                'code' => 'sr',
                'name' => 'српски језик',
                'english_name' => 'Serbian',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            141 => 
            array (
                'id' => 142,
                'code' => 'gd',
                'name' => 'Gàidhlig',
                'english_name' => 'Gaelic, Scottish Gaelic',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            142 => 
            array (
                'id' => 143,
                'code' => 'sn',
                'name' => 'chiShona',
                'english_name' => 'Shona',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            143 => 
            array (
                'id' => 144,
                'code' => 'si',
                'name' => 'සිංහල',
                'english_name' => 'Sinhala, Sinhalese',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            144 => 
            array (
                'id' => 145,
                'code' => 'sk',
                'name' => 'Slovenčina, Slovenský Jazyk',
                'english_name' => 'Slovak',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            145 => 
            array (
                'id' => 146,
                'code' => 'sl',
                'name' => 'Slovenski Jezik, Slovenščina',
                'english_name' => 'Slovenian',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            146 => 
            array (
                'id' => 147,
                'code' => 'so',
                'name' => 'Soomaaliga, af Soomaali',
                'english_name' => 'Somali',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            147 => 
            array (
                'id' => 148,
                'code' => 'st',
                'name' => 'Sesotho',
                'english_name' => 'Southern Sotho',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            148 => 
            array (
                'id' => 149,
                'code' => 'es',
                'name' => 'Español',
                'english_name' => 'Spanish, Castilian',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            149 => 
            array (
                'id' => 150,
                'code' => 'su',
                'name' => 'Basa Sunda',
                'english_name' => 'Sundanese',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            150 => 
            array (
                'id' => 151,
                'code' => 'sw',
                'name' => 'Kiswahili',
                'english_name' => 'Swahili',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            151 => 
            array (
                'id' => 152,
                'code' => 'ss',
                'name' => 'SiSwati',
                'english_name' => 'Swati',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            152 => 
            array (
                'id' => 153,
                'code' => 'sv',
                'name' => 'Svenska',
                'english_name' => 'Swedish',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            153 => 
            array (
                'id' => 154,
                'code' => 'ta',
                'name' => 'தமிழ்',
                'english_name' => 'Tamil',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            154 => 
            array (
                'id' => 155,
                'code' => 'te',
                'name' => 'తెలుగు',
                'english_name' => 'Telugu',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            155 => 
            array (
                'id' => 156,
                'code' => 'tg',
                'name' => 'тоҷикӣ, toçikī, تاجیکی',
                'english_name' => 'Tajik',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            156 => 
            array (
                'id' => 157,
                'code' => 'th',
                'name' => 'ไทย',
                'english_name' => 'Thai',
                'status_public' => 'enabled',
                'status_staff' => 'enabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            157 => 
            array (
                'id' => 158,
                'code' => 'ti',
                'name' => 'ትግርኛ',
                'english_name' => 'Tigrinya',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            158 => 
            array (
                'id' => 159,
                'code' => 'bo',
                'name' => 'བོད་ཡིག',
                'english_name' => 'Tibetan',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            159 => 
            array (
                'id' => 160,
                'code' => 'tk',
                'name' => 'Türkmen, Түркмен',
                'english_name' => 'Turkmen',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            160 => 
            array (
                'id' => 161,
                'code' => 'tl',
                'name' => 'Wikang Tagalog',
                'english_name' => 'Tagalog',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            161 => 
            array (
                'id' => 162,
                'code' => 'tn',
                'name' => 'Setswana',
                'english_name' => 'Tswana',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            162 => 
            array (
                'id' => 163,
                'code' => 'to',
                'name' => 'Faka Tonga',
            'english_name' => 'Tonga (Tonga Islands)',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            163 => 
            array (
                'id' => 164,
                'code' => 'tr',
                'name' => 'Türkçe',
                'english_name' => 'Turkish',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            164 => 
            array (
                'id' => 165,
                'code' => 'ts',
                'name' => 'Xitsonga',
                'english_name' => 'Tsonga',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            165 => 
            array (
                'id' => 166,
                'code' => 'tt',
                'name' => 'татар теле, tatar tele',
                'english_name' => 'Tatar',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            166 => 
            array (
                'id' => 167,
                'code' => 'tw',
                'name' => 'Twi',
                'english_name' => 'Twi',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            167 => 
            array (
                'id' => 168,
                'code' => 'ty',
                'name' => 'Reo Tahiti',
                'english_name' => 'Tahitian',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            168 => 
            array (
                'id' => 169,
                'code' => 'ug',
                'name' => 'ئۇيغۇرچە‎, Uyghurche',
                'english_name' => 'Uighur, Uyghur',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            169 => 
            array (
                'id' => 170,
                'code' => 'uk',
                'name' => 'Українська',
                'english_name' => 'Ukrainian',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            170 => 
            array (
                'id' => 171,
                'code' => 'ur',
                'name' => 'اردو',
                'english_name' => 'Urdu',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            171 => 
            array (
                'id' => 172,
                'code' => 'uz',
                'name' => 'Oʻzbek, Ўзбек, أۇزبېك',
                'english_name' => 'Uzbek',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            172 => 
            array (
                'id' => 173,
                'code' => 've',
                'name' => 'Tshivenḓa',
                'english_name' => 'Venda',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            173 => 
            array (
                'id' => 174,
                'code' => 'vi',
                'name' => 'Tiếng Việt',
                'english_name' => 'Vietnamese',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            174 => 
            array (
                'id' => 175,
                'code' => 'vo',
                'name' => 'Volapük',
                'english_name' => 'Volapük',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            175 => 
            array (
                'id' => 176,
                'code' => 'wa',
                'name' => 'Walon',
                'english_name' => 'Walloon',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            176 => 
            array (
                'id' => 177,
                'code' => 'cy',
                'name' => 'Cymraeg',
                'english_name' => 'Welsh',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            177 => 
            array (
                'id' => 178,
                'code' => 'wo',
                'name' => 'Wollof',
                'english_name' => 'Wolof',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            178 => 
            array (
                'id' => 179,
                'code' => 'fy',
                'name' => 'Frysk',
                'english_name' => 'Western Frisian',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            179 => 
            array (
                'id' => 180,
                'code' => 'xh',
                'name' => 'isiXhosa',
                'english_name' => 'Xhosa',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            180 => 
            array (
                'id' => 181,
                'code' => 'yi',
                'name' => 'ייִדיש',
                'english_name' => 'Yiddish',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            181 => 
            array (
                'id' => 182,
                'code' => 'yo',
                'name' => 'Yorùbá',
                'english_name' => 'Yoruba',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            182 => 
            array (
                'id' => 183,
                'code' => 'za',
                'name' => 'Saɯ cueŋƅ, Saw cuengh',
                'english_name' => 'Zhuang, Chuang',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
            183 => 
            array (
                'id' => 184,
                'code' => 'zu',
                'name' => 'isiZulu',
                'english_name' => 'Zulu',
                'status_public' => 'disabled',
                'status_staff' => 'disabled',
                'created_at' => '2019-10-02 16:22:42',
                'updated_at' => NULL,
            ),
        ));
         
    }
}
